/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Dao;
import entities.Cliente;
import entities.User;
import fn.Boton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import fn.Icons;
import fn.OptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author home
 */
public class VUsuarios extends javax.swing.JPanel {
    Boton boton = new Boton();
    Dao load= new Dao();
    /**
     * Creates new form VClientes
     */
    public VUsuarios() {
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboMostrar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        btnAbrir = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JLabel();
        pnlAddUser = new javax.swing.JPanel();
        lblNewName = new javax.swing.JLabel();
        lblNewUsername = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        txtNewUsername = new javax.swing.JTextField();
        lblNewEmail = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        lblNewType = new javax.swing.JLabel();
        cboNewTipo = new javax.swing.JComboBox<>();
        lblNewPass = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JTextField();
        pnlUpdateUser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        txtUpdateUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUpdateEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cboUpdateType = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUpdatePass = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        cboMostrar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cboMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activos", "Eliminados" }));
        cboMostrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMostrarItemStateChanged(evt);
            }
        });

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Username", "Email", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListar);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Eye_50px.png"))); // NOI18N
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Trash_50px.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Data_Backup_50px.png"))); // NOI18N
        btnRestaurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestaurarMouseExited(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Web_Search_25px.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Web_Search_25px.png"))); // NOI18N
        btnBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAbrir)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pnlAddUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Agregar usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        lblNewName.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblNewName.setText("Nombre");

        lblNewUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblNewUsername.setText("Username");

        txtNewName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewNameKeyTyped(evt);
            }
        });

        txtNewUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewUsernameKeyTyped(evt);
            }
        });

        lblNewEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblNewEmail.setText("Email");

        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });
        txtNewEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewEmailKeyTyped(evt);
            }
        });

        lblNewType.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblNewType.setText("Tipo");

        cboNewTipo.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        cboNewTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNewPass.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblNewPass.setText("Contraseña");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Save_50px.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        txtNewPass.setEditable(false);
        txtNewPass.setText("Optica2018");
        txtNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPassActionPerformed(evt);
            }
        });
        txtNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlAddUserLayout = new javax.swing.GroupLayout(pnlAddUser);
        pnlAddUser.setLayout(pnlAddUserLayout);
        pnlAddUserLayout.setHorizontalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddUserLayout.createSequentialGroup()
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblNewUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNewType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNewName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNewPass))
                .addGap(4, 4, 4)
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNewName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtNewUsername)
                    .addComponent(cboNewTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPass))
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddUserLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNewEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddUserLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addContainerGap())))
        );
        pnlAddUserLayout.setVerticalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddUserLayout.createSequentialGroup()
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddUserLayout.createSequentialGroup()
                        .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewName)
                            .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewUsername)
                            .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewEmail)
                            .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboNewTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNewType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewPass)
                            .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlUpdateUser.setBackground(new java.awt.Color(108, 217, 186));
        pnlUpdateUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Abrir usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel10.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel11.setText("Username");

        txtUpdateName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdateNameKeyTyped(evt);
            }
        });

        txtUpdateUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdateUsernameKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel13.setText("Email");

        txtUpdateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateEmailActionPerformed(evt);
            }
        });
        txtUpdateEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdateEmailKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel17.setText("Sexo");

        cboUpdateType.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        cboUpdateType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Save_50px.png"))); // NOI18N
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel19.setText("Contraseña");

        txtUpdatePass.setEditable(false);
        txtUpdatePass.setText("Optica2018");
        txtUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdatePassActionPerformed(evt);
            }
        });
        txtUpdatePass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdatePassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlUpdateUserLayout = new javax.swing.GroupLayout(pnlUpdateUser);
        pnlUpdateUser.setLayout(pnlUpdateUserLayout);
        pnlUpdateUserLayout.setHorizontalGroup(
            pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUpdateName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtUpdateUsername))
                            .addComponent(cboUpdateType, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUpdatePass)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addComponent(txtUpdateEmail)
                        .addGap(10, 10, 10))
                    .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addContainerGap())))
        );
        pnlUpdateUserLayout.setVerticalGroup(
            pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlUpdateUserLayout.createSequentialGroup()
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtUpdateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cboUpdateType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar)
                    .addGroup(pnlUpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtUpdatePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailActionPerformed

    private void txtUpdateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateEmailActionPerformed

    private void txtNewNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewNameKeyTyped
        int largo = 45;
        if(txtNewName.getText().length() >= largo){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El nombre solo debe contener hasta 45 caracteres", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNewNameKeyTyped

    private void txtNewUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewUsernameKeyTyped
        int largo = 45;
        if(txtNewUsername.getText().length() >= largo){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El username solo debe contener hasta 45 caracteres", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNewUsernameKeyTyped

    private void txtNewEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewEmailKeyTyped
        int largo = 45;
        if(txtNewEmail.getText().length() >= largo){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El email solo debe contener hasta 45 caracteres", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNewEmailKeyTyped

    private void txtUpdateNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateNameKeyTyped
        int largo = 45;
        if(txtUpdateName.getText().length() >= largo || txtUpdateName.getText().length()<= largo-1){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El nombre solo debe contener hasta 45 caracteres", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtUpdateNameKeyTyped

    private void txtUpdateUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateUsernameKeyTyped
        int largo = 45;
        if(txtUpdateUsername.getText().length() >= largo){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El username solo debe contener hasta 45 caracteres", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtUpdateUsernameKeyTyped

    private void txtUpdateEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateEmailKeyTyped
        int largo = 45;
        if(txtUpdateEmail.getText().length() >= largo){
            evt.consume();
            OptionPane.showMsg("Error de ingreso de datos", "El email solo debe contener hasta 45 caracteres", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtUpdateEmailKeyTyped

    private void btnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseClicked
        try{
            int fila = tblListar.getSelectedRow();
            String username = tblListar.getValueAt(fila, 1).toString();
            
            abrirUsuario(username);
            
        }catch(Exception e){
            OptionPane.showMsg("Seleccione usuario", "Debe seleccionar un usuario", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAbrirMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try{
            int fila = tblListar.getSelectedRow();
            String username = tblListar.getValueAt(fila, 1).toString();
            User temp = (User)load.get(username, 0, new User());
            if(OptionPane.getConfirmation("Eliminar usuario", "¿Estas seguro que deseas eliminar al usuario "+temp.getNombre()+"?", JOptionPane.WARNING_MESSAGE)){
                if(load.delete(username, 0, temp)){
                    OptionPane.showMsg("Eliminar usuario", "El usuario ha sido eliminado", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    OptionPane.showMsg("Eliminar usuario", "No se pudo eliminar el usuario", JOptionPane.WARNING_MESSAGE);
                }
                cargarDatos("");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario", "Seleccione usuario", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnRestaurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseClicked
        try{
            int fila = tblListar.getSelectedRow();
            String username = tblListar.getValueAt(fila, 1).toString();
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea restaurar este usuario?");
            if(OptionPane){
                if(load.restore(username, 0, new User())){
                    JOptionPane.showMessageDialog(null, "El cliente ha sido restaurado", "Restaurar Cliente", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo restaurar el cliente", "Restaurar Cliente", JOptionPane.WARNING_MESSAGE);
                }
                cargarDatos("eliminados");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente", "Seleccione Cliente", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaurarMouseClicked

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnAbrir.getIcon().toString()))));
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnAbrir.getIcon().toString()))));
    }//GEN-LAST:event_btnAbrirMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnEliminar.getIcon().toString()))));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnEliminar.getIcon().toString()))));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnRestaurarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseEntered
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnRestaurar.getIcon().toString()))));
    }//GEN-LAST:event_btnRestaurarMouseEntered

    private void btnRestaurarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarMouseExited
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnRestaurar.getIcon().toString()))));
    }//GEN-LAST:event_btnRestaurarMouseExited

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        String buscar = txtBuscar.getText();
        buscarDatos(buscar,1);
        limpiarTextField();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnBuscar.getIcon().toString()))));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnBuscar.getIcon().toString()))));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseClicked
        String buscar = txtBuscar.getText();
        buscarDatos(buscar,0);
        limpiarTextField();
    }//GEN-LAST:event_btnBuscar1MouseClicked

    private void btnBuscar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseEntered
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnBuscar1.getIcon().toString()))));
    }//GEN-LAST:event_btnBuscar1MouseEntered

    private void btnBuscar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseExited
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnBuscar1.getIcon().toString()))));
    }//GEN-LAST:event_btnBuscar1MouseExited

    private void cboMostrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMostrarItemStateChanged
        load();
    }//GEN-LAST:event_cboMostrarItemStateChanged

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String rut=txtNewName.getText();
        FnValidaRut vr = new FnValidaRut();
        if(vr.validarRut(rut)){
            String nombre=txtNewUsername.getText();
            System.out.println("|"+txtTelefonoNew1.getText()+"|");
            String telefono=txtTelefonoNew1.getText();
            if(!txtTelefonoNew2.getText().equals("")){
                if(txtTelefonoNew1.getText().equals("")){
                    telefono = txtTelefonoNew2.getText();
                }else{
                    telefono=txtTelefonoNew1.getText() + " / " + txtTelefonoNew2.getText();
                }
            }
            String mail=txtNewEmail.getText();
            String direccion=txtDireccionNew.getText().toUpperCase();
            String comuna=txtComunaNew.getText().toUpperCase();
            String ciudad=txtCiudadNew.getText().toUpperCase();
            int sexo=cboNewTipo.getSelectedIndex();
            int edad=(int) txtEdadNew.getValue();
            int estado=1;

            Cliente cliente= new Cliente(rut, nombre, telefono, mail, direccion, comuna, ciudad, sexo, edad, estado);
            FnCliente fn = new FnCliente();
            String mensaje="ERROR";
            try {
              mensaje=fn.guardar(cliente);  
            } catch (Exception e) {
                mensaje="ERROR"+e;
            }

            JOptionPane.showMessageDialog(null, mensaje, "Guardar Cliente", JOptionPane.INFORMATION_MESSAGE);
            cargarDatos("");
        }else{
            JOptionPane.showMessageDialog(null, "El rut ingresado no existe", "Guardar Cliente", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnGuardar.getIcon().toString()))));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnGuardar.getIcon().toString()))));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        String rut = txtUpdateName.getText();
        String nombre= txtUpdateUsername.getText();
        String telefono = txtTelefono1.getText();
        if(txtTelefono2.getText().length() > 7){
            if(txtTelefono1.getText().length() < 7){
                telefono = txtTelefono2.getText();
            }else{
                telefono=txtTelefono1.getText() + " / " + txtTelefono2.getText();
            }
        }
        String email = txtUpdateEmail.getText();
        String direccion = txtDireccion.getText().toUpperCase();
        String comuna = txtComuna.getText().toUpperCase();
        String ciudad = txtCiudad.getText().toUpperCase();
        int sexo = cboUpdateType.getSelectedIndex();
        int edad = (int) txtEdad.getValue();
        int estado = 1;
        
        Cliente cliente = new Cliente(rut, nombre, telefono, email, direccion, comuna, ciudad, sexo, edad, estado);
        FnCliente load = new FnCliente();
        try {
            if(load.modificar(cliente))
                JOptionPane.showMessageDialog(null, "Operación realizada con exito", "Modificar Cliente", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "No se pudo efectuar la operación", "Modificar Cliente", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Modificar Cliente", JOptionPane.WARNING_MESSAGE);Logger.getLogger(VUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Modificar Cliente", JOptionPane.WARNING_MESSAGE);Logger.getLogger(VUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargarDatos("");
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnModificar.getIcon().toString()))));// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnModificar.getIcon().toString()))));// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseExited

    private void txtNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPassActionPerformed

    private void txtNewPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPassKeyTyped

    private void txtUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdatePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatePassActionPerformed

    private void txtUpdatePassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdatePassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatePassKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbrir;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnBuscar1;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnRestaurar;
    private javax.swing.JComboBox<String> cboMostrar;
    private javax.swing.JComboBox<String> cboNewTipo;
    private javax.swing.JComboBox<String> cboUpdateType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNewEmail;
    private javax.swing.JLabel lblNewName;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNewType;
    private javax.swing.JLabel lblNewUsername;
    private javax.swing.JPanel pnlAddUser;
    private javax.swing.JPanel pnlUpdateUser;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JTextField txtUpdateEmail;
    private javax.swing.JTextField txtUpdateName;
    private javax.swing.JTextField txtUpdatePass;
    private javax.swing.JTextField txtUpdateUsername;
    // End of variables declaration//GEN-END:variables

    private void cargarCbos(){
        
        cboUpdateType.removeAllItems();
        cboUpdateType.addItem("Sin Seleccionar");
        cboUpdateType.addItem("Femenino");
        cboUpdateType.addItem("Masculino");
        cboNewTipo.removeAllItems();
        cboNewTipo.addItem("Sin Seleccionar");
        cboNewTipo.addItem("Femenino");
        cboNewTipo.addItem("Masculino");
    }
    
    private void load(){
        if(cboMostrar.getSelectedIndex()==0){//en nueva version cargar ventana completa con lista de clientes estatica global
            cargarDatos("0");
        }else{
            cargarDatos("-1");
        }
    }
    private void cargarDatos(String listar) {
        cargarCbos();
        limpiarTextField();
        if(listar.equals("-1")){
            btnRestaurar.setVisible(true);
            btnEliminar.setVisible(false);
            btnAbrir.setVisible(false);
            btnModificar.setVisible(false);
            btnBuscar.setVisible(false);
            btnBuscar1.setVisible(true);
        }else{
            btnRestaurar.setVisible(false);
            btnEliminar.setVisible(true);
            btnAbrir.setVisible(true);
            btnModificar.setVisible(true);
            btnBuscar.setVisible(true);
            btnBuscar1.setVisible(false);
        }
            
        txtUpdateName.setEditable(false);
        DefaultTableModel modelo;
        modelo = new DefaultTableModel() {
           @Override
           public boolean isCellEditable(int fila, int columna) {
               return false; //Con esto conseguimos que la tabla no se pueda editar
           }
        };
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Username");
        modelo.addColumn("Email");
        modelo.addColumn("Tipo");
        tblListar.setModel(modelo);
        
        int cont =0;
        try{
            for (Object object : load.listar(listar, new User())) {
                User temp = (User)object;
                String tipo = "No asignado";
                switch (temp.getTipo()){
                    case 1:
                        tipo = "Administrador";
                        break;
                    case 2:
                        tipo = "Vendedor";
                        break;
                    case 3:
                        tipo = "Inventario";
                        break;
                    default:
                        break;
                }
                Object[] fila = new Object[4];
                fila[0] = temp.getNombre();
                fila[1] = temp.getUsername();
                fila[2] = temp.getEmail();
                fila[3] = tipo;
                modelo.addRow(fila);
            }
            tblListar.updateUI();
            if(tblListar.getRowCount() == 0){
                OptionPane.showMsg("Sin registros", "No existen usuarios registrados", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(Exception e){
            OptionPane.showMsg("Error de registros", "Error, ["+e.getMessage()+"]", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirUsuario(String username) throws SQLException, ClassNotFoundException {
            FnCliente load = new FnCliente();
            Cliente temp = load.cargar(rut);
            if(temp!=null){
                txtUpdateName.setText(temp.getRut());
                if(temp.getNombre().equals("null"))
                    txtUpdateUsername.setText("");
                else
                    txtUpdateUsername.setText(temp.getNombre());
                if(temp.getCiudad().equals("null"))
                    txtCiudad.setText("");
                else
                    txtCiudad.setText(temp.getCiudad());;
                if(temp.getComuna().equals("null"))
                    txtComuna.setText("");
                else
                    txtComuna.setText(temp.getComuna());
                if(temp.getDireccion().equals("null"))
                    txtDireccion.setText("");
                else
                    txtDireccion.setText(temp.getDireccion());
                txtEdad.setValue(temp.getEdad());
                if(temp.getTelefono().equals("null")){
                    txtTelefono1.setText("");
                    txtTelefono2.setText("");
                }
                else{
                    if(temp.getTelefono().contains("/")){
                        int ind = temp.getTelefono().indexOf("/");
                        txtTelefono1.setText(temp.getTelefono().substring(0, ind).replace("/", "").trim());
                        txtTelefono2.setText(temp.getTelefono().substring(ind, temp.getTelefono().length()).replace("/", "").trim());
                    }else
                        txtTelefono1.setText(temp.getTelefono());
                } 
                if(temp.getEmail().equals("null"))
                    txtUpdateEmail.setText("");
                else
                    txtUpdateEmail.setText(temp.getEmail());
                
                cboUpdateType.setSelectedIndex(temp.getSexo());
                
            }else{
                JOptionPane.showMessageDialog(null, "Error al cargar el cliente", "Seleccione Cliente", JOptionPane.INFORMATION_MESSAGE);
            }
    }

    private void buscarDatos(String buscar, int i) {
        DefaultTableModel modelo;
        modelo = new DefaultTableModel() {
           @Override
           public boolean isCellEditable(int fila, int columna) {
               return false; //Con esto conseguimos que la tabla no se pueda editar
           }
        };
        
        modelo.addColumn("Rut");
        modelo.addColumn("Nombre");
        modelo.addColumn("Email");
        modelo.addColumn("Teléfonos");
        tblListar.setModel(modelo);
        FnCliente datbd= new FnCliente();
        int cont =0;
        try{
            for (Cliente temp : datbd.buscar(buscar,i)) {
                Object[] fila = new Object[4];
                fila[0] = temp.getRut();
                fila[1] = temp.getNombre();
                fila[2] = temp.getEmail();
                fila[3] = temp.getTelefono();
                modelo.addRow(fila);
            }
            tblListar.updateUI();
            if(tblListar.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "No se encontraron resultados, pruebe con otros valores de búsqueda.");
                if(i == 1){
                    cargarDatos("");
                }else{
                    cargarDatos("eliminados");
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, ["+e.getMessage()+"]");
        }
    }

    private void limpiarTextField() {
        txtUpdateName.setText("");
        txtCiudad.setText("");
        txtComuna.setText("");
        txtDireccion.setText("");
        txtEdad.setValue(4);
        txtUpdateEmail.setText("");
        txtUpdateUsername.setText("");
        txtTelefono1.setText("");
        txtTelefono2.setText("");
        cboUpdateType.removeAllItems();
        cboUpdateType.addItem("Sin Seleccionar");
        cboUpdateType.addItem("Femenino");
        cboUpdateType.addItem("Masculino");
        txtNewName.setText("");
        txtCiudadNew.setText("");
        txtComunaNew.setText("");
        txtDireccionNew.setText("");
        txtEdadNew.setValue(4);
        txtNewEmail.setText("");
        txtNewUsername.setText("");
        txtTelefonoNew1.setText("");
        txtTelefonoNew2.setText("");
        cboNewTipo.removeAllItems();
        cboNewTipo.addItem("Sin Seleccionar");
        cboNewTipo.addItem("Femenino");
        cboNewTipo.addItem("Masculino");
    }
}
